version: '3.8'

services:
  task-manager:
    image: your-task-manager-image:latest
    container_name: task-manager
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=youruser
      - DATABASE_PASSWORD=yourpassword
      - DATABASE_NAME=yourdatabase
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: task-manager-db
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdatabase
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: